Document: xbmc-pvr-addons
Title: Debian xbmc-pvr-addons Manual
Author: <insert document author here>
Abstract: This manual describes what xbmc-pvr-addons is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xbmc-pvr-addons/xbmc-pvr-addons.sgml.gz

Format: postscript
Files: /usr/share/doc/xbmc-pvr-addons/xbmc-pvr-addons.ps.gz

Format: text
Files: /usr/share/doc/xbmc-pvr-addons/xbmc-pvr-addons.text.gz

Format: HTML
Index: /usr/share/doc/xbmc-pvr-addons/html/index.html
Files: /usr/share/doc/xbmc-pvr-addons/html/*.html
